@HotelListing.API_HostAddress = https://localhost:7166

GET {{HotelListing.API_HostAddress}}/api/hotels
Accept: application/json

###
###
PUT {{HotelListing.API_HostAddress}}/api/hotels/3
Content-Type: application/json

{
  "name": "Grand Hotel Brussels Updated",
  "address": "Rue Royale 100, 1000 Bruxelles",
  "rating": 4,
  "countryId": 1
}
###
@id=0
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
	"name": "Grand Hotel Brussels Updated",
	"address": "Rue Royale 100, 1000 Bruxelles",
	"rating": 4.8,
	"countryId": 1
}
###
GET {{HotelListing.API_HostAddress}}/api/countries

###
GET {{HotelListing.API_HostAddress}}/api/countries/1

###
GET {{HotelListing.API_HostAddress}}/api/countries/999

### 
POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Belgique",
  "code": "BE"
}

###
PUT {{HotelListing.API_HostAddress}}/api/countries/1
Content-Type: application/json

{
  "name": "United States of America",
  "code": "US"
}

###
DELETE {{HotelListing.API_HostAddress}}/api/countries/5