name: Build .NET Core application

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: '10.0.x'
  WORKING_DIRECTORY: HotelListing.API
  PACKAGE_PATH: '${{ github.workspace }}/publish'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish API
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --output ${{ env.PACKAGE_PATH }} --no-build

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PACKAGE_PATH }}
